### ISSUE TITLE
Prototype pollution in funcster.js

### ISSUE THREAD

**Issue by lelecolacola123** [jeffomatic/funcster#4]
Prototype pollution vulnerability in function _generateModule in nfuncster/js/lib/funcster.js in funcster 0.0.5.
Because use the vm VMS in the _generateModule function, line 141 passes insecure script information to the opts object lead to prototype pollution

**Comment by jeffomatic** [comment]
A security warning covers this concern:

https://github.com/jeffomatic/funcster#security-warning
